### ISSUE TITLE
Macro attack not working on V10

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#160]
Hi,

i'm not sure this is usefull, and may be you are already working on it (V10).

When i try to use the Attack Macro i have 2 errors :  the use of the actor variable (can be easilly passed, by renaming it) and the property equipped that seems not working anymore on object or powers.

if you already know that or working on it, feel free to close the issue.

Good work and all my support for readingt this.

Best regards

**Comment by lipefl** [comment]
Hi, i wasn't aware. It's fixed in v1.10.5
Thanks!

**Comment by Arnok13** [comment]
i have still an issue with the let actor = ....
i havec to rename that varaible to have the macro works 
with let actorbis = ... and replace all the occurrence of actor with actorbis except the last work of the let : let actorbis=canvas.tokens.controlled[0]?.actor

otherwise the console says : Uncaught (in promise) SyntaxError: Identifier 'actor' has already been declared

thanks again

**Comment by aedgaruk** [comment]
Hi,

re: attack macro in 1.10.5 even after delete/refresh I still get this error thrown (see image):

![image](https://user-images.githubusercontent.com/111492074/194113948-70d0e3d1-b0bf-44b7-abf3-e5b0534842ac.png)

..  Line 4:

![image](https://user-images.githubusercontent.com/111492074/194114224-8e9ea0f4-038e-4374-8067-9577907edb5d.png)

Cheers
Andy

**Comment by aedgaruk** [comment]
Apologies, I think I dropped my post as Arnok13 did his ... I think mine is a duplicate.

**Comment by Arnok13** [comment]
just rename the actor (from the let) with something else and the macro works fine.

**Comment by aedgaruk** [comment]
Can you cut and paste me an example please?

**Comment by aedgaruk** [comment]
Hi, that's not working for me ...

![image](https://user-images.githubusercontent.com/111492074/194129033-659ddafd-d170-4e12-80b9-8a370a942751.png)

... going to wait on lipefl as presumably we'd like any correction to be made at module level for everyone.

Thank You anyway tho' ... appreciate the thought.
Andy :)

**Comment by Arnok13** [comment]
V10 ? may be the copy/paste on github fails.

just replace in the original macro the "actor", with another name (i choose "actorbis") except the last one on the first code line (this one is a property).

**Comment by Arnok13** [comment]
there was an actor still not modified, i correct it.

**Comment by lipefl** [comment]
This is not happening here. But since it's the easier path, I'll update the macro in the next update.

**Comment by Arnok13** [comment]
it works fine now ! Thanx.
