### ISSUE TITLE
Dead Extra still count on Gang-up bonus

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#259]
Hi,
last night i see that dead extra are still counting for gang up.
They are well removed from turn order.

i try to force a Dead status, but nothing change.

![image](https://github.com/lipefl/swade-tools/assets/4520046/b7832007-632f-42e0-b2e6-dd0c65850b87)

**Comment by lipefl** [comment]
Hi,
I made a similar test and it works as intended. 
Wich versions of Foundry / SWADE system / SWADE Tools are you using? Is everything updated?

![image](https://github.com/lipefl/swade-tools/assets/10639148/70fcdb4d-baef-44a7-9727-81d9526c5793)

**Comment by Arnok13** [comment]
can it be a module conflict ? or a migration error on tokens ?

**Comment by lipefl** [comment]
You can try to replicate the error with only swade tools enabled. That's how i tested it. 
Also, try a new actor, new world. If it works, it's probably a bug in this particular scenario.

**Comment by Arnok13** [comment]
on another world, tonight i reproduce the bug (may be due to migration). I will try on a new world.
![image](https://github.com/lipefl/swade-tools/assets/4520046/4efa7970-7db9-4c90-8f63-5131e3d6b864)

**Comment by Arnok13** [comment]
test with new things and it produced again :

![image](https://github.com/lipefl/swade-tools/assets/4520046/ac069f51-b29b-4214-b322-e79311ce0b54)

**Comment by Arnok13** [comment]
it seems it only works if the token is marked as defeated in the turn order (but not always - something must interfere with that) :

![image](https://github.com/lipefl/swade-tools/assets/4520046/6f9693c4-73bb-4940-9560-4df00818f9e3)

**Comment by lipefl** [comment]
You found it! I was testing using the turn order. 
I tried with wounds and it counts the defeated token for gang up. I'll look into it. Thanks!

**Comment by lipefl** [comment]
Fixed in v1.14.3
Thanks!

**Comment by Arnok13** [comment]
just find why it was still not working : Active effect that are not in english are now translated.

So the "Incapacitated" active Effect is "Incapacité" in French.

If i change the name in the JS it works perfectly.

**Comment by lipefl** [comment]
Thanks! I can add the translated term automatically.
I'll reopen this issue to remind myself.

**Comment by lipefl** [comment]
Fixed in v1.16.6. 
Thanks!
