### ISSUE TITLE
Chat roll message buttons not working anymore with Chrome 117

### ISSUE THREAD

**Issue by LeRatierBretonnien** [lipefl/swade-tools#260]
With Chrome/Chrome Beta 117+, the roll chat message buttons are not working anymore.

![image](https://github.com/lipefl/swade-tools/assets/1085008/39390827-1024-4873-956e-76ec2191c594)

When the buttons are clicked, the details rolls result are displayed, instead of the relevant roll actions (ie bennies, rerolls, etc).

Note that it works with Chromium 116 and Firefox, so it seems related to Chrome 117+

A user in the Foundry US Discord with the same problem suspects a Z-Order/CSS issue.

**Comment by 7thSim** [comment]
same issue with Microsoft Edge.

**Comment by lipefl** [comment]
Fixed in v1.14.3
Thanks!

**Comment by 7thSim** [comment]
Still have the issue, using Chrome, Edge and Brave. All have the problem.

**Comment by lipefl** [comment]
@7thSim I tested again, it's working on chrome and edge. Can you check your versions of SWADE system and Foundry?
Im using
Foundry 11.309
SWADE System 3.1.4

Also, try disabling all other modules and see if it works. If you still have problems, let me know.

**Comment by LeRatierBretonnien** [comment]
This issue is still there, since Chrome 117+ and derivatives. It works with Chrome 116+.
Tested again with no module at all : 

![image](https://github.com/lipefl/swade-tools/assets/1085008/82b16703-a675-4f38-9ae1-4d5161be15a3)

When you click on the buttons pointed by the arrows, it unfold the dice results, like this  : 

![image](https://github.com/lipefl/swade-tools/assets/1085008/cac97ace-0014-4cc4-a5e8-64a578b14077)

**Comment by LeRatierBretonnien** [comment]
I confirm, problem fixed, thanks  !

**Comment by 7thSim** [comment]
doh! I had to force update my edge - now it works. Thanks for all your work.
