### ISSUE TITLE
NPCs get hit notifications, but players do not

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#88]
As seen in the screenshot below. When I attack with an NPC, it resolves a hit against parry and gives me the ability to roll damage, etc. But when attacking with a PC, it does not. This, regardless of the weapon or spell used.

![image](https://user-images.githubusercontent.com/69117052/145701989-4c3203af-400f-40f1-bffb-b34cc6b21920.png)

![image](https://user-images.githubusercontent.com/69117052/145702081-a39f71aa-8579-41d6-ab72-b41bcbbb07b3.png)

**Comment by lipefl** [comment]
Is there any errors in the console? Can you send me?

**Comment by gravagehulk** [comment]
![image](https://user-images.githubusercontent.com/69117052/145718773-969b13e0-6491-426c-a35a-c745286c125d.png)

**Comment by lipefl** [comment]
Can you inform your version of Foundry and Swade System?

**Comment by gravagehulk** [comment]
The newest available on Stable: 0.21.4. Foundry is 0.8.9

**Comment by lipefl** [comment]
Please open you NPC token configuration and see if this field is correct or "none"
![image](https://user-images.githubusercontent.com/10639148/145827766-ea375f41-15c7-4adb-93f3-0dcca6f0f2d9.png)

Sorry for asking so many things, it's because i can't reproduce your error here. So i am trying to find where it comes from.

**Comment by gravagehulk** [comment]
No worries. Anything I can do to help.

It is set correctly (i.e. Bear is set to "Bear", Orc is set to "Orc", etc.

**Comment by gravagehulk** [comment]
Here is a screenshot of my modules. I have a few others, but most of what isn't shown here are things like map packs, etc.

![image](https://user-images.githubusercontent.com/69117052/145833517-aee40290-6f84-4dd7-a0e4-cf5a4a021870.png)

**Comment by lipefl** [comment]
I was finally able to reproduce the problem. Thanks.
v1.6.2 should solve it.

**Comment by gravagehulk** [comment]
> I was finally able to reproduce the problem. Thanks. v1.6.2 should solve it.

So, ranged attacks are working from PCs now (bow, pitol, etc), but melee attacks are still not generating a "hit" result. It's just outputting totals.

![image](https://user-images.githubusercontent.com/69117052/145872142-c8f83467-4480-48ff-b796-49894c138654.png)

**Comment by lipefl** [comment]
Is there any console errors?

**Comment by gravagehulk** [comment]
![image](https://user-images.githubusercontent.com/69117052/145874984-e42c569f-9cc6-4a23-a90a-e0cfbc6f07fc.png)

**Comment by lipefl** [comment]
Fixed now in v1.6.3

**Comment by gravagehulk** [comment]
That seems to have finally done the trick. Thank you!
